### ISSUE TITLE
Cursor Not Showing on OSX

### ISSUE THREAD

**Issue by jasonkeene** [jasonkeene/github-data-viz#12]

**Comment by jasonkeene** [comment]
@JrManfre I found a fix for this on this issue: https://github.com/openframeworks/openFrameworks/issues/3052

All you need to do is:
1. Open up the ofAppGLFWWindow.cpp
2. Find the method void ofAppGLFWWindow::motion_cb
3. Add these three lines to the top:

``` C
#ifdef TARGET_OSX
    [(NSWindow*)ofGetCocoaWindow() resetCursorRects];
#endif
```

**Comment by barrylachapelle** [comment]
Nice one @jasonkeene

**Comment by dimitre** [comment]
Thanks!
