### ISSUE TITLE
Repository Node repulsion

### ISSUE THREAD

**Issue by jasonkeene** [jasonkeene/github-data-viz#4]
The RepositoryNode's should repel each other so they don't overlap.

**Comment by alejandroman** [comment]
I'll try this one, sounds like a physics based feature. Right now I'm trying to see if i can run the code with VS12 on windows 7

**Comment by alejandroman** [comment]
Jason, do you have the file "ofMain.h"?

**Comment by jasonkeene** [comment]
@alejandroman ofMain.h is part of openframeworks. You will need to tell VS where to find the openframeworks stuff.

We got code::blocks to build with this workspace: https://github.com/jasonkeene/github-data-viz/blob/master/github_data_viz.workspace You might want to just download code::blocks and use that. There are instructions on canvas on how to get everything to build.

**Comment by alejandroman** [comment]
Ok, i had it almost run with vc12, right now is not compiling due to icon.rc file that it can't open. But i'll try with code::blocks now.

**Comment by jasonkeene** [comment]
Yeah, I removed the icon.rc file in this commit: https://github.com/jasonkeene/github-data-viz/commit/76567c26e7b2dc0782ade4b55c138187068e9d21#diff-e22f1fa08d051a976d8418b29a1949f7

If you want to add it back you can download it here: https://raw.githubusercontent.com/jasonkeene/github-data-viz/824edc4b8de9a2d2a2af4935617c8845d6d939ab/icon.rc

Sorry, I didn't think it would break your build.

**Comment by alejandroman** [comment]
That's ok, i couldn't get either one (VS12 and code::blocks) to run on my desktop despite the instructions; I honestly don't know what I'm doing wrong. I'll ask Andrew to show me how he did it in his laptop and i'll try to get it to run tomorrow.

**Comment by alejandroman** [comment]
Ok i finally got it to build with codeblocks and it turned out easier than what i thought. I haven't tested this method with VS12 but I'm positive it will work too. I'm going to add it to the documentation right now. 
From what i seen in the build, the nodes already seem to repulse each other. Did you added this feature recently?

**Comment by jasonkeene** [comment]
The repository nodes repel from the language nodes but not from each other.
