### ISSUE TITLE
Langauge Nodes should layout themselves

### ISSUE THREAD

**Issue by jasonkeene** [jasonkeene/github-data-viz#5]
Currently they are just randomly placed and you can drag them around but they should just automatically layout.

**Comment by andrewdci03** [comment]
I would like to work on this, however, I'm not sure exactly how this would be done. Anything to get me started would be great!

**Comment by jasonkeene** [comment]
This should be implemented as the step function of the LanguageNode:

https://github.com/jasonkeene/github-data-viz/blob/2119cf217bb1c4660bdf74e5823e806e71598a91/src/LanguageNode.cpp#L15-L18

An idea I had was to have the LanguageNodes repel each other and the magnitude of the repulsive force would be based on the size of the LanguageNode. So when step() gets called on a specific LanguageNode it will need to look at all the other LanguageNodes and figure out the appropriate acceleration vector. When a node gets to the edge of the window you can just flip the vector to send it away from the edge. Eventually acceleration and velocity will go to 0 and everything will be laid out.

If you have troubles with this we can pair on it. I'll be on campus Friday.

**Comment by andrewdci03** [comment]
I will be at work, but maybe we can through skype/teamviewer this weekend on that function.

**Comment by jasonkeene** [comment]
FYI @JrManfre did some work on this today.
